spring.application.name: simple-secure-service

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: simplesecure

app:
  echo:
    max-params: 10
